import type {
  RelayConfig,
  GatewayRequest,
  GatewayResponse,
  GatewayEvent,
  GatewayFrame,
  ConnectParams,
  ClientId,
  ClientMode,
  HelloOkPayload,
  PresenceEntry,
  PairingRequestResponse,
  PairingStatusResponse,
  ConnectionState,
  MessagePart,
  TextPart,
  ImagePart,
} from '@openclaw/shared';

export type {
  RelayConfig,
  GatewayRequest,
  GatewayResponse,
  GatewayEvent,
  GatewayFrame,
  ConnectParams,
  ClientId,
  ClientMode,
  HelloOkPayload,
  PresenceEntry,
  PairingRequestResponse,
  PairingStatusResponse,
  ConnectionState,
  MessagePart,
  TextPart,
  ImagePart,
};
